// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgnLQc4PU-WqKWPBpdE6HgMKi42KkBC6E',
    appId: '1:329448846553:web:9d5de608ea051a17bf3ac8',
    messagingSenderId: '329448846553',
    projectId: 'futsal-go-6c47b',
    authDomain: 'futsal-go-6c47b.firebaseapp.com',
    storageBucket: 'futsal-go-6c47b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiziYqj5AmBRqMwng_CU_WHwIwn4T4WW8',
    appId: '1:329448846553:android:cf3b9bf1dfea124fbf3ac8',
    messagingSenderId: '329448846553',
    projectId: 'futsal-go-6c47b',
    storageBucket: 'futsal-go-6c47b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkzhmxdiuIzyR_L0qxtpBtHhhwrApekY',
    appId: '1:329448846553:ios:2f213a0fe03c1dbcbf3ac8',
    messagingSenderId: '329448846553',
    projectId: 'futsal-go-6c47b',
    storageBucket: 'futsal-go-6c47b.firebasestorage.app',
    iosBundleId: 'com.example.futsalGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkzhmxdiuIzyR_L0qxtpBtHhhwrApekY',
    appId: '1:329448846553:ios:2f213a0fe03c1dbcbf3ac8',
    messagingSenderId: '329448846553',
    projectId: 'futsal-go-6c47b',
    storageBucket: 'futsal-go-6c47b.firebasestorage.app',
    iosBundleId: 'com.example.futsalGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgnLQc4PU-WqKWPBpdE6HgMKi42KkBC6E',
    appId: '1:329448846553:web:aec17bf6ca57a25fbf3ac8',
    messagingSenderId: '329448846553',
    projectId: 'futsal-go-6c47b',
    authDomain: 'futsal-go-6c47b.firebaseapp.com',
    storageBucket: 'futsal-go-6c47b.firebasestorage.app',
  );
}
